AWSTemplateFormatVersion: '2010-09-09'
Description: 'vpc setup bySundhar'

Parameters:

  Environment:
    Type: String
    AllowedValues:
    - Dev
    - Production

  VpcName:
      Type: String

  VpcCIDR:
      Type: String

  publicSubnet1CIDR:
      Type: String
  publicSubnet2CIDR:
      Type: String
  publicSubnet3CIDR:
      Type: String

  privateSubnet1CIDR:
      Type: String
  privateSubnet2CIDR:
      Type: String
  privateSubnet3CIDR:
      Type: String

Mappings:

  AZMap:
    AZ1:
      Index: 0
    AZ2:
      Index: 1
    AZ3:
      Index: 2

Conditions:
  Isprod: !Equals: [!Ref Environment, Production]

Resources:
  paramName: MyVPC
    Type: AWS::EC2::VPC
    properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-${Environment}

  paramName: InternetGateway
    Type: AWS::EC2::InternetGateway
    properties:
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-IGW-${Environment}

  paramName: VPCGatewayAttachment
    Type: AWS::EC2::VPCGatewayAttachment
    properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref InternetGateway

  
  publicsubnet1:
    Type: AWS::EC2::Subnet
    properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref publicSubnet1CIDR
      AvailabilityZone: !Select [!FindInMap [AZMap, AZ1, Index], !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PublicSubnet1-${Environment}

  publicsubnet2:
    Type: AWS::EC2::Subnet
    properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref publicSubnet2CIDR
      AvailabilityZone: !Select [!FindInMap [AZMap, AZ2, Index], !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PublicSubnet2-${Environment}

  publicsubnet3:
    Type: AWS::EC2::Subnet
    Conditions: IsProd
    properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref publicSubnet3CIDR
      AvailabilityZone: !Select [!FindInMap [AZMap, AZ3, Index], !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PublicSubnet3-${Environment}    

  privatesubnet1:
    Type: AWS::EC2::Subnet
    properties:              
      VpcId: !Ref MyVPC
      CidrBlock: !Ref privateSubnet1CIDR
      AvailabilityZone: !Select [!FindInMap [AZMap, AZ1, Index], !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PrivateSubnet1-${Environment}

  privatesubnet2:
    Type: AWS::EC2::Subnet
    properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref privateSubnet2CIDR
      AvailabilityZone: !Select [!FindInMap [AZMap, AZ2, Index], !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PrivateSubnet2-${Environment}  

  privatesubnet3:
    Type: AWS::EC2::Subnet
    Conditions: IsProd
    properties:
      VpcId: !Ref MyVPC
      CidrBlock: !Ref privateSubnet3CIDR
      AvailabilityZone: !Select [!FindInMap [AZMap, AZ3, Index], !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PrivateSubnet3-${Environment}  

  publicrouteTable:
    Type: AWS::EC2::RouteTable
    properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PublicRouteTable-${Environment}

  privateRouteTable:
    Type: AWS::EC2::RouteTable
    properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: !Sub
            - ${VpcName}-PrivateRouteTable-${Environment}
  
  publicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    properties:
      RouteTableId: !Ref publicrouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway 

  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    properties:
      SubnetId: !Ref publicsubnet1
      RouteTableId: !Ref publicrouteTable   

  publicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    properties:
      SubnetId: !Ref publicsubnet2
      RouteTableId: !Ref publicrouteTable 

  publicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Conditions: IsProd
    properties:
      SubnetId: !Ref publicsubnet3
      RouteTableId: !Ref publicrouteTable 

  privateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation   
    properties:
      SubnetId: !Ref privatesubnet1
      RouteTableId: !Ref privateRouteTable  

  privateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    properties:
      SubnetId: !Ref privatesubnet2
      RouteTableId: !Ref privateRouteTable  

  privateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation   
    Conditions: IsProd
    properties:
      SubnetId: !Ref privatesubnet3   
      RouteTableId: !Ref privateRouteTable  